export const CHAT_SEND_MESSAGE = 'CHAT_SEND_MESSAGE'
export const CHAT_GET_MESSAGES = 'CHAT_GET_MESSAGES'
export const CHAT_DISSCONNENT = 'CHAT_DISSCONNENT'
export const CHAT_NEW_MESSAGES = 'CHAT_NEW_MESSAGES'

export const USER_LOGIN_STATUS = 'USER_LOGIN_STATUS'
